spring.application.name=bd
#   Conexão com PostgreSQL #
spring.datasource.url=jdbc:postgresql://localhost:5432/produtos-db
spring.datasource.username=postgres
spring.datasource.password=postgres
# JPA - Hibernate #
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true